# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  soTimeout: 1501
  connectTimeout: 601 
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
    - 172.16.200.101:22122 